# Generated by Django 4.0.5 on 2022-06-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProg', '0002_remove_orders_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.CharField(default='default title', max_length=100),
            preserve_default=False,
        ),
    ]
